<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
#default: --format profile features
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
# Used when Autotest wants to run only the failing scenarios:
autotest: --color <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
# Used when Autotest wants to run all the scenarios (after a red→green transition).
autotest-all: --color <%= std_opts %> features
html_report: --format progress --format html --out=features_report.html features
